### ISSUE TITLE
Some unicode characters should be escaped before save

### ISSUE THREAD

**Issue by vdanchenkov** [bahmutov/snap-shot-core#13]
I got `"\u2028"` in my test data. Snapshot was saved with it as single unescaped character, but on the second run I got error 'SyntaxError: Invalid or unexpected token'. I'm not sure which characters could cause problems.

We could fix this specific case or use a more general approach like  https://github.com/mathiasbynens/jsesc.

**Comment by bahmutov** [comment]
That's a good suggestion to use escape library!

**Comment by bahmutov** [comment]
Should be https://github.com/bahmutov/snap-shot-core/releases/tag/v1.7.3
