### ISSUE TITLE
Outputting snapshots on the first line is not user friendly

### ISSUE THREAD

**Issue by brian-mann** [bahmutov/snap-shot-core#27]
![screen shot 2017-09-04 at 12 22 27 pm](https://user-images.githubusercontent.com/1268976/30033872-0ef589ea-916c-11e7-9008-6c85dac89801.png)

I would much prefer the first part of the snapshot to begin on its own line.

I would actually properly prefer moving these all to `markdown` and using three backticks to represent the snapshot.

As it stands even trying to find snapshots is difficult with the test titles being so long.

**Comment by bahmutov** [comment]
Moving multiline text to next line could be simple, although it is a breaking change for existing snapshot files.

**Comment by bahmutov** [comment]
Version `5.0.0` has been published to NPM. The full release note can be found at [snap-shot-core/releases/tag/v5.0.0](https://github.com/bahmutov/snap-shot-core/releases/tag/v5.0.0).

**Tip:** safely upgrade dependency snap-shot-core in your project using [next-update](https://github.com/bahmutov/next-update)

**Comment by bahmutov** [comment]
https://github.com/bahmutov/snap-shot-core#text-snapshots
