### ISSUE TITLE
Expected and Actual are confusing

### ISSUE THREAD

**Issue by brian-mann** [bahmutov/snap-shot-core#28]
Oftentimes I find myself confused when a snapshot fails.

When I see `Expected` and `Actual` I'm confused which is which.

In chai we get this...
```
expect('foo').to.eq('bar')
AssertionError: expected 'foo' to equal 'bar'
```

And that makes sense because we're being explicit about the `to.eq('bar')`.

The problem is that there is no comparison here.

I suggest renaming `Actual text` to be something like `Existing Snapshot Text`

**Comment by bahmutov** [comment]
Issue moved to [bahmutov/snap-shot-it #17](https://github.com/bahmutov/snap-shot-it/issues/17) via [**ZenHub**](https://www.zenhub.com/)
