### ISSUE TITLE
Request: allow tests in different directories to share basenames

### ISSUE THREAD

**Issue by mcous** [bahmutov/snap-shot-core#32]
Related issue: bahmutov/snap-shot-it#26

I'm hoping to use `snap-shot-it` (and, by extension, `snap-shot-core`) in a mocha-tested project that could benefit from snapshot testing. I ran into some problems, however, with the existing default snapshot location of `cwd/__snapshots__`:

1. I'm unable to have unrelated test files in different directories share a name
    * In my specific case, I'm working in a monorepo
    * Several packages in the project each have a test file named `render.test.js`
2. The snapshot location changes depending on where in the repo I am when I run tests
    * I may want to run all tests from the repo root, or...
    * I may want to run my snapshots when I'm `cd`d into `packages/some-project`

(1) is easy enough to work around by naming the test files differently, and (2) I can workaround by always running tests from repo root. Neither of those are particularly onerous, but both feel arbitrary. A few possibilities for solutions came to my mind when reading over the code here:

1. Change FS default to `/path/to/test-dir/__snapshots__/filename.js`
    * This makes the most sense to me
    * Looking at other snapshot libraries, this is how [jest][], [ava][], and [snapshotter][] operate
2. Change FS default to `cwd/__snapshots__/path/to/test-dir/filename.js`
    * This seems a little awkward to me
    * Would get the job done, though
3. Keep current default, add an option that takes a function `(filename) => snapshotLocation`
    * Since the option is a function, it's harder for `snap-shot-it` (or whatever) to pass something in from the environment or JSON
4. Something else entirely?

I'm more than happy to open a PR for this, but before I do anything @bahmutov I'd like to hear your thoughts on whether you view these "problems" as worth addressing and, if so, what your desired solution would be. Thanks for your time!

[jest]: https://github.com/facebook/jest/tree/master/examples/snapshot/__tests__
[ava]: https://github.com/avajs/ava#snapshot-testing
[snapshotter]: https://github.com/cdlewis/snapshotter

**Comment by bahmutov** [comment]
So I am working on PR #254 where I think we will store snapshots with structure mimicking nested path to the spec file:

if the test.js is nested from the current working directory

```
specs/
  subfolder/
     test.js
```

then the snapshot will be stored in

```
__snapshots__/
  specs/
     subfolder/
         test.js.snapshot.js
```
