### ISSUE TITLE
Disallow saving snapshots on CI

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/snap-shot-core#5]
Makes no sense to save new data on CI, the snapshots should be committed by the developer, otherwise the test checks nothing.

Most CIs set environment variable `CI`, so if we pass it as an option to this module, it should disallow saving new value or updating existing snapshot

* https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
* https://circleci.com/docs/1.0/environment-variables/
* https://docs.gitlab.com/ce/ci/variables/#predefined-variables-environment-variables

**Comment by brian-mann** [comment]
Need a way to override this behavior. There are situations where libs may simulate being in CI (such as ours) without REALLY being in CI.

In this scenario the tests fail.
